# Docker on Travis requires sudo.
sudo: required

install:
  - sudo pip install -r requirements.txt
script:
  - sudo ./test_runner.sh

after_success:
  - codecov
  - REPO=scottx611x/refinery-higlass-docker
  - IMAGE=`sudo docker ps --latest --format '{{ .Image }}'` # TODO: with more containers, can't rely on ordering
  - tag_push() { echo "Tagging into $2"; sudo docker tag $1 $2; sudo docker push $2; }

  - sudo docker login -u $DOCKER_USER -p $DOCKER_PASS
  # Always update "latest": the cache will be used for the next build.
  - tag_push $IMAGE $REPO
  - >
      if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then
        echo "PR!";

        BRANCH=`echo ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} | perl -pne 'chomp;s{.*/}{};s/\W/-/g'`;
        tag_push $IMAGE $REPO:$BRANCH;
        tag_push $IMAGE $REPO:latest-pr;
      fi
  - >
      if [ ! -z "$TRAVIS_TAG" ]; then
        echo "Git tag!";
        tag_push $IMAGE $REPO:$TRAVIS_TAG;
        tag_push $IMAGE $REPO:latest;
      fi

notifications:
 email:
    recipients:
      - Scott_Ouellette@hms.harvard.edu
    on_success: never
    on_failure: always
env:
  global:
  - secure: r3GsMiK82N3X9IC5fE9u1VgU9DfsPQFYFk9gVuA4zYgBk3gBhZPhROqcyS4BRQWP96DhZA/H7uR8i1YlwvrW5FICH/qU95wzCIu1n7A6nmXi0YZQIC3Fy1WrXsuFWb2eG/UA6fyV2976aHI23jopsZMNYNgNCT/W2alieLk0kiHNh7SNsfYzra16Wzx+jQOKExmWtziBPnSckO0p63fDtlBAkAh9v+yB4jZI3D9cULMgT/IQ4v+Z2lVo5wgzzRUUnU2ougG3Lsefm4O0pA7QdNfKEfyv132SiSVcOTudcvmk6pMh/QFfF5/LzIcnN1eh6cppzzEk8+DsduUjjgtl2rXn74BAIOZrjtuJx2Q1pPD+KBv0pp51wMceyuX1ossDuamvokokP1somtnH8uaIPG4aBT3SpdTrO1yIo+gaWFykZS9ctM04gai1KBwc+qBq8WjE3yK6k+PdKb9xyIK8riCK4rgGMefDMIF7ebTcEGIQM+Wl+48PvINoh7t796F+81sT0Zph3jVMOXkOttceUWLZTDnhN5sisD0AVvD4SvM6fHfytH0jmH0cRyTuLxRNj4fPERO9e1PVA7o3AvfGs+bB8KlVNtz8YuPKhNRz9TJApasIM36MilvE2GPF71LWLleHavuGJwHPAhJsM8UMlvHijFK6WtdmSVmApZ8cwyY=
  - secure: YxS3uqyGNAnacaM6cnvk5fcvm//kFPwdibsRDy1FOxKYzuujU16UmkD+8osRPZTbajOWkUPyoLeNAwuKpBemm+DgCdXps7so/OHj7AkiV6zAP+5W3trlAPdbCApOnu6J5abBsaC7OZOIR+3V8swNbeE9I+YgpvmiRFRDnrqIvmqxzUti0UhmNzADMBWnllQ0FV5GeKYJ4kiyGKwIr9FSWPn4mH/HX2QKagcNbyWu4mBqdiQMucqbwRpIkPquoCakORecWNqrrjXWn0q8Owbaq0cYJMdN7TlUanqQzbxg4db1kIiyD1XNFQLjWWj5538VjKP0TQ8nf0X45KkNw6hExrPSeOtwcvBnVlwr9VzV7OZuZomQ43KGtnZENhfAEj2kk0T4w1Drq3DZmQ6p4YpWehfR1s44lXPuIyggpjGk88RbobQ4aHTNC+5na+nf3NqyIJYIbZ42R1nHI6YsIX/N72csmixeTvgrcBy60HbiGoZN4rmdPqDItE5vjUF9uUcwBCBHjGNchA/RzwZ7g/tSgMFVA0dr2a+DnLQk9jukFdkagmZmiMQn0BEq5b68Gi5sd4jCmJFRE23FCY6TReCie+XYQcHbuIGQFpREPIbkop0moLdd6PWankV6ge/LcUhWSkd1iZQHsWLUl7BD67wF0zcEoNONIOGOdCmVYRRakHg=
